-- 016: Ficha de Identificação — novos campos do prontuário
ALTER TABLE pacientes
  ADD COLUMN IF NOT EXISTS sexo VARCHAR(20),
  ADD COLUMN IF NOT EXISTS estado_civil VARCHAR(30),
  ADD COLUMN IF NOT EXISTS nacionalidade VARCHAR(50) DEFAULT 'Brasileira',
  ADD COLUMN IF NOT EXISTS filiacao TEXT,
  ADD COLUMN IF NOT EXISTS indicacao VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cep VARCHAR(10),
  ADD COLUMN IF NOT EXISTS rua VARCHAR(200),
  ADD COLUMN IF NOT EXISTS numero_endereco VARCHAR(20),
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
  ADD COLUMN IF NOT EXISTS estado_uf VARCHAR(2);
